name: android-build

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      JAVA_HOME_17_X64: /opt/hostedtoolcache/jdk/17.0.8/x64
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Ensure Gradle available (install if necessary)
        run: |
          if [ -x "./gradlew" ]; then
            echo "Gradle wrapper exists, will use ./gradlew"
          else
            echo "No gradlew found — installing gradle via apt"
            sudo apt-get update
            sudo apt-get install -y gradle
          fi

      - name: Grant execute permission for gradlew if exists
        run: |
          if [ -f "./gradlew" ]; then chmod +x ./gradlew; fi

      - name: Build Debug APK
        run: |
          if [ -x "./gradlew" ]; then
            ./gradlew assembleDebug --no-daemon
          else
            gradle assembleDebug --no-daemon
          fi

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
